[package]
name = "linfa-logistic"
version = "0.2.1"
authors = ["Paul Körbitz / Google <koerbitz@google.com>"]

description = "A Machine Learning framework for Rust"
edition = "2018"
license = "MIT/Apache-2.0"

repository = "https://github.com/rust-ml/linfa"
readme = "README.md"

keywords = ["machine-learning", "linfa", "ai", "ml", "linear"]
categories = ["algorithms", "mathematics", "science"]

[dependencies]
ndarray = {version = "0.13", features = ["approx", "blas"]}
ndarray-linalg = "0.12"
num-traits = "0.2"
argmin = {version="0.3.1", features=["ndarrayl"]}
serde = "1.0"

linfa = { version = "0.2.1", path = ".." }

[dev-dependencies]
approx = "0.3.2"
